name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:  # (optional) Run workflow manually
  push: {branches: ["main"]} # (optional) Run workflow when pushing on master/main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      # - uses: lowlighter/metrics@latest
      #   with:
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     template: markdown
      #     # filename: metrics.repository.svg
      #     user: dniald
      #     # repo: metrics
      #     plugin_lines: yes
      #     plugin_activity: yes
      #     # plugin_followup: yes

      - name: markdown
        uses: lowlighter/metrics@latest
        with:
          template: markdown
          filename: metrics.markdown.md
          markdown: >-
            https://raw.githubusercontent.com/lowlighter/metrics/examples/metrics.markdown.template.md
          config_output: markdown
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          # plugin_languages_ignored: >-
          #   html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
          #   gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 20
          plugin_languages_analysis_timeout: 15
        
      - name: Compact display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
