name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:  # (optional) Run workflow manually
  push: {branches: ["main"]} # (optional) Run workflow when pushing on master/main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      # - uses: lowlighter/metrics@latest
      #   with:
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     template: markdown
      #     # filename: metrics.repository.svg
      #     user: dniald
      #     # repo: metrics
      #     plugin_lines: yes
      #     plugin_activity: yes
      #     # plugin_followup: yes

      - name: markdown
        uses: lowlighter/metrics@latest
        with:
          template: markdown
          filename: metrics.markdown.md
          markdown: >-
            https://raw.githubusercontent.com/lowlighter/metrics/examples/metrics.markdown.template.md
          config_output: markdown
          token: ${{ secrets.METRICS_TOKEN }}
